### ISSUE TITLE
Disappearing bucket

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#30] opened 2023-10-03 03:37 UTC
**Description:**
The red bucket required for progression disappears, blocking progression completely. (This might be fixed if we overhaul this part of the puzzle completely.)

**To reproduce:**
Unclear. However what we observed at PGF:

1.  Take bucket from child
2. Bring bucket to exchange for donut
3. Leave the screen for an extended period of time
4. Return - the bucket is gone

**Additional Notes**
Suspected it is to do with the child that picks up the bucket not working correctly, or objects floating through the floor. If we change the puzzle to not be the bucket but instead respawnable treasures this will become obsolete.

**Comment by ZachariaWinter** [comment] 2023-10-03 05:41
I have created an object catcher which will; respawn the bucklet in its starting postion if it falls below the world.
For the time being I will not close this issue, as ideally the bucket never falls through the world in the first place.

It should not longer lock the palyer out of finishing the level, but the problem is not 'solved'.

**Comment by ZachariaWinter** [comment] 2023-10-09 02:28
![image](https://github.com/FoodAbuse/stabo-crabo-game/assets/127712819/cd88a3e8-18ae-48cd-8909-6d2fa678ba59)
Running tests, the bucket is not staying with the child's hand as they walk, it gets further and further from them and swings with the walking animation, eventually it starts to clip into the ground
![image](https://github.com/FoodAbuse/stabo-crabo-game/assets/127712819/8fc3feab-e0a4-4c60-a0db-4045318a2d32)

In this particular case, the child dropped the bucket at a high point and it did not clip through, but I can easily see how it could happen

**Comment by ZachariaWinter** [comment] 2023-10-09 03:17
Ran a bunch of tests.
![image](https://github.com/FoodAbuse/stabo-crabo-game/assets/127712819/e418e99d-5453-403e-9436-bb0e5ee43317)

Conclusion:
Interpolation settigns caused the bucket to drift from the wrist parent, which combined with the swing of the child's arm caused the bucket to swing with an increasing amplitude. When the bucket is dropped at the trough of the swing, the bucket is clipped through the floor and dissapears.

Solved through turning interpolate to 'none'.

**Closed by ZachariaWinter** 2023-10-09 03:17 UTC
Labels: bug, Priority: Urgent!
